kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: canary
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  args:
  - name: namespace
  - name: route-url
  - name: api-token
    valueFrom:
      secretKeyRef:
        name: monitor-auth-secret
        key: token
  metrics:
  - name: success-rate
    interval: 20s
    count: 3
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] == 0
    failureLimit: 0
    provider:
      prometheus:
        address: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
        timeout: 40
        insecure: true
        headers:
          - key: Authorization
            value: "Bearer {{args.api-token}}"
        query: |
          irate(istio_requests_total{destination_service_namespace='{{args.namespace}}',destination_service=~"canary-canary.*", response_code!="200"}[1m]) > 5 or on() vector(0)
  - name: run-load
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            metadata:
              labels:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
              - name: siege
                image: quay.io/gnunn/tools:latest
                command: [sh, -c]
                args: ["siege -c 20 -r 10 -d5 -v http://{{args.route-url}}"]
              restartPolicy: Never
